version: '3'
services:
  frontend:
    build: client
    container_name: client
    image: genesis-client
    restart: always
    ports:
      - 5001:5001
    stdin_open: true
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    build: server
    container_name: server
    image: genesis-server
    restart: always
    ports:
      - 5002:5002
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
    expose:
      - 27017
networks:
  react-express:
  express-mongo:
